image: docker:latest

variables:
  VERSION: "0.0.1"

.build_template:
  stage: build
  variables:
    DOCKER_IMAGE: "$CI_REGISTRY_IMAGE"
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo $EMAIL
    - docker build --no-cache --pull --build-arg NPM_TOKEN --build-arg NPM_EMAIL -t $DOCKER_IMAGE:$VERSION .
    - docker push $DOCKER_IMAGE:$VERSION
    - docker tag "$DOCKER_IMAGE:$VERSION" "$DOCKER_IMAGE:latest"
    - docker push "$DOCKER_IMAGE:latest"
  only:
    - master

build app:
  extends: .build_template

deploy:
  image: alpine
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - mkdir -p ~/.ssh
    - apk --update add openssh-client git
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - scp docker-compose.yaml node@95.217.3.180:~
    - ssh -o "BatchMode yes" node@95.217.3.180 "docker login -u gitlab -p $TOKEN $CI_REGISTRY && cd ~ && docker-compose pull && docker-compose up -d"
  when: manual
  only:
    - master
